const buttonsArray = [
    {
     name:"(",
     symbol:"(",
     color:"default",
     variant:"outlined"   
    },
    {
     name:")",
     symbol:")",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"CE",
     symbol:"CE",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"C",
     symbol:"C",
     color:"secondary",
     variant:"contained"   
    },
    {
     name:"7",
     symbol:"7",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"8",
     symbol:"8",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"9",
     symbol:"9",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"÷",
     symbol:"/",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"4",
     symbol:"4",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"5",
     symbol:"5",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"6",
     symbol:"6",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"*",
     symbol:"*",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"1",
     symbol:"1",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"2",
     symbol:"2",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"3",
     symbol:"3",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"-",
     symbol:"-",
     color:"default",
     variant:"outlined"   
    },
    {
     name:".",
     symbol:".",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"0",
     symbol:"0",
     color:"default",
     variant:"outlined"   
    },
    {
     name:"=",
     symbol:"=",
     color:"primary",
     variant:"contained"   
    },
    {
     name:"+",
     symbol:"+",
     color:"default",
     variant:"outlined"   
    },
]
export default buttonsArray;